# Generated by Django 3.1.3 on 2020-11-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('bio', models.CharField(max_length=350)),
                ('jobrole', models.CharField(max_length=50)),
            ],
        ),
    ]
